apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: devops-toolkit
spec:
  components:
  - name: backend
    type: backend
    properties:
      image: alpine
      cmd:
      - sleep
      - "1000000"
  - name: frontend
    type: frontend
    properties:
      name: frontend
      image: 071494471915.dkr.ecr.us-east-1.amazonaws.com/devops-toolkit-series:1.0.0
    traits:
    - type: autoscaler
      properties:
        min: 3
    - type: ingress
      properties:
        domain: localhost
        http:
          "/": 80
